### ISSUE TITLE
Problems with UI

### ISSUE THREAD

**Issue by dielsonsales** [matt-allen/repay-android#3]
On my Xperia E, some UI elements don't fit very well (my screen is 480 x 320).

![](http://i.imgur.com/5jH7kQn.png)
![](http://i.imgur.com/J56cZTk.png)

**Comment by matt-allen** [comment]
Thanks for showing me this, there is a material design update coming once I have the time to finish it which should solve problems like this. Hopefully, it should reach the Play Store in the next 2 months.

**Comment by dielsonsales** [comment]
Just letting you know that I fixed the layout problems in my device (I'm learning Android and lately decided to take on this project to work on a real code base), though I don't think you'll be interested in merging it, since you're already very advanced in in the develo branch compared to the stable master.

But anyway, if you need some help, I'll be glad to make it better if you tell me what you'd like me to work on. Apparently you started making some changes in the design and didn't finish, since it seems to lack some references and doesn't compile?
